"""How many distinct terms are in the sequence
generated by a^b for 2 <= a <= 100
and 2 <= b <= 100?"""

import math
from timeit import default_timer as timer


def distinct_powers(a_max, b_max):
    products = set()
    for a in range(2, a_max + 1):
        for b in range(2, b_max + 1):
            products.add(a**b)
    return len(products)

start = timer()
ans = distinct_powers(100, 100)
elapsed_time = (timer() - start) * 1000  # s --> ms

print("\nFound %d in %d ms.\n" % (ans, elapsed_time))
